apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: license-service
  labels:
    app: license-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: license-service
    spec:
      containers:
      - name: license-service
        image: "qlikea/license-service:0.2.0"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9200
        env:
        - name: LEF_SERIAL
          value: <LEF serial number here>
        - name: LEF_CONTROL
          value: <LEF control number here>
      imagePullSecrets:
      - name: dockerhub
