version: "3.0"

services:
  mira:
    # Mira is our QIX Engine Discovery Service. It provides internal
    # APIs to list (or query) all available QIX Engine containers
    # in the cluster.
    # See https://github.com/qlik-ea/mira
    image: qlikea/mira:0.0.2-396
    ports:
      - 9100:9100
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints: [node.role == manager]

  qix-engine:
    # QIX Engine is configured to run on all worker nodes in the
    # cluster, and is the service we primarily want to scale up in
    # this use-case.
    image: qlikea/engine:12.51.0
    ports:
      - 9076:9076
      - 9090:9090
    labels:
      qix-engine: ""

  license-service:
    # License service is used to valiate a license and to unlock the QIX Engine service.
    image: qlikea/license-service:0.0.1-361
    ports:
      - 9200:9200