version: "3.3"

services:
  mira:
    # Mira is our QIX Engine Discovery Service. It provides internal
    # APIs to list (or query) all available QIX Engine containers
    # in the cluster.
    # See https://github.com/qlik-ea/mira
    image: qlikea/mira:0.0.1-263
    command: --mode=swarm
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints: [node.role == manager]

  qix-engine:
    # QIX Engine is configured to run on all worker nodes in the
    # cluster, and is the service we primarily want to scale up in
    # this use-case.
    image: qlikea/engine:12.51.0
    labels:
      qix-engine: ""
      qix-engine-port: "9076"
    deploy:
      mode: global
      placement:
        constraints: [node.role == worker]

