version: "3.0"

services:
  mira:
    image: qlikea/mira:0.1.0
    ports:
      - 9100:9100
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints: [node.role == manager]

  qix-engine:
    image: qlikea/engine:12.145.0
    deploy:
      replicas: 2
    command: -S AcceptEULA=${ACCEPT_EULA} -S LicenseServiceUrl=http://license-service:9200
    ports:
      - 9076:9076
      - 9090:9090
    labels:
      qix-engine: ""

  license-service:
    image: qlikea/license-service:0.3.0
    ports:
      - 9200:9200
