apiVersion: v1
kind: Service
metadata:
  name: license-service
  labels:
    app: license-service
spec:
  type: NodePort
  ports:
    - port: 5050
      targetPort: 5050
      protocol: TCP
      name: http
  selector:
    app: license-service