version: 2
jobs:
  build:
    machine: true
    environment:
      CHANGE_MINIKUBE_NONE_USER: true
    working_directory: ~/core
    steps:
      - checkout
      - run:
          name: Install Helm
          command: |
            curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get > get_helm.sh
            chmod 700 get_helm.sh
            ./get_helm.sh
      - run:
          name: Lint charts
          command: |
            helm lint ./Kubernetes/Helm/frontira
            helm lint ./Kubernetes/Helm/frontira/charts/engine
            helm lint ./Kubernetes/Helm/frontira/charts/mira
            helm lint ./Kubernetes/Helm/frontira/charts/license-service
      - run:
          name: Install Kubectl
          command: |
            curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.7.0/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
      - run:
          name: Install Minikube
          command: |
            curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
      - run:
          name: Start Minikube
          command: |
            sudo minikube start --vm-driver=none --kubernetes-version=v1.7.0
            sudo minikube update-context
      - run:
          name: Install socat (needed by helm)
          command: sudo apt-get install socat
      - run:
          name: Install nsenter (needed by helm)
          command: |
            cd /tmp; curl https://www.kernel.org/pub/linux/utils/util-linux/v2.25/util-linux-2.25.tar.gz | tar -zxf-; cd util-linux-2.25;
            sudo apt-get install autopoint autoconf libtool automake
            ./configure --without-python --disable-all-programs --enable-nsenter --without-ncurses
            sudo make nsenter; sudo cp nsenter /usr/local/bin
      - run:
          name: Add docker credentials as kubernetes secret
          command: sudo kubectl create secret docker-registry dockerhub --docker-username=$DOCKER_USER --docker-password=$DOCKER_PASSWORD --docker-email=$DOCKER_EMAIL
      - run:
          name: Helm init and wait for tiller to be running
          command: sudo helm init --debug; sudo kubectl rollout status -w deployment/tiller-deploy --namespace=kube-system;
      - run:
          name: Helm install frontira
          command: sudo helm install ./Kubernetes/Helm/frontira --set global.setType=NodePort --name test --debug
      - run:
          name: Check health of services
          command: |
            # Check mira health
            MIRA_URL=$(sudo minikube service test-mira --url)
            curl -fs "$MIRA_URL/v1/health"
            # Check license service health
            LICENSE_SERVICE_URL=$(sudo minikube service test-license-service --url)
            curl -fs "$LICENSE_SERVICE_URL/v1/health"
      - run:
          name: Helm delete frontira
          command: sudo helm delete test --debug
      - run:
          name: Kubernetes plain frontira
          command: sudo kubectl create -f ./Kubernetes/Plain/frontira/
      - run:
          name: Check health of services
          command: |
            # Check mira health
            MIRA_URL=$(sudo minikube service mira --url)
            curl -fs "$MIRA_URL/v1/health"
            # Check license service health
            LICENSE_SERVICE_URL=$(sudo minikube service license-service --url)
            curl -fs "$LICENSE_SERVICE_URL/v1/health"
      - run:
          name: Kubernetes delete frontira
          command: sudo kubectl delete -f ./Kubernetes/Plain/frontira/
