version: 2
jobs:

  # Job for testing helm and plain kubernetes deployment of core
  kubernetes:
    machine: true
    environment:
      CHANGE_MINIKUBE_NONE_USER: true
    working_directory: ~/core
    steps:
      - checkout
      - run:
          name: Install Helm
          command: |
            curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get > get_helm.sh
            chmod 700 get_helm.sh
            ./get_helm.sh
      - run:
          name: Lint charts
          command: |
            helm lint ./Kubernetes/Helm/frontira
            helm lint ./Kubernetes/Helm/frontira/charts/engine
            helm lint ./Kubernetes/Helm/frontira/charts/mira
            helm lint ./Kubernetes/Helm/frontira/charts/license-service
      - run:
          name: Install Kubectl
          command: |
            curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.7.0/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
      - run:
          name: Install Minikube
          command: |
            curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
      - run:
          name: Start Minikube
          command: |
            sudo minikube start --vm-driver=none --kubernetes-version=v1.7.0
            sudo minikube update-context
      - run:
          name: Install socat (needed by helm)
          command: |
            sudo apt-get update
            sudo apt-get install socat
      - run:
          name: Install nsenter (needed by helm)
          command: |
            cd /tmp; curl https://www.kernel.org/pub/linux/utils/util-linux/v2.25/util-linux-2.25.tar.gz | tar -zxf-; cd util-linux-2.25;
            sudo apt-get install autopoint autoconf libtool automake
            ./configure --without-python --disable-all-programs --enable-nsenter --without-ncurses
            sudo make nsenter; sudo cp nsenter /usr/local/bin
      - run:
          name: Add docker credentials as kubernetes secret
          command: sudo kubectl create secret docker-registry dockerhub --docker-username=$DOCKER_USER --docker-password=$DOCKER_PASSWORD --docker-email=$DOCKER_EMAIL
      - run:
          name: Helm init and wait for tiller to be running
          command: sudo helm init --debug; sudo kubectl rollout status -w deployment/tiller-deploy --namespace=kube-system;
      - run:
          name: Helm install frontira
          command: sudo helm install ./Kubernetes/Helm/frontira --set global.setType=NodePort --name test --debug
      - run:
          name: Check health of services
          command: |
            # Check mira health
            MIRA_URL=$(sudo minikube service test-mira --url)
            curl -fs "$MIRA_URL/v1/health"
            # Check license service health
            LICENSE_SERVICE_URL=$(sudo minikube service test-license-service --url)
            curl -fs "$LICENSE_SERVICE_URL/v1/health"
      - run:
          name: Helm delete frontira
          command: sudo helm delete test --debug
      - run:
          name: Kubernetes plain frontira
          command: sudo kubectl create -f ./Kubernetes/Plain/frontira/
      - run:
          name: Check health of services
          command: |
            # Check mira health
            MIRA_URL=$(sudo minikube service mira --url)
            curl -fs "$MIRA_URL/v1/health"
            # Check license service health
            LICENSE_SERVICE_URL=$(sudo minikube service license-service --url)
            curl -fs "$LICENSE_SERVICE_URL/v1/health"
      - run:
          name: Kubernetes delete frontira
          command: sudo kubectl delete -f ./Kubernetes/Plain/frontira/

  # Job for testing docker swarm deployment of core
  swarm:
    machine: true
    working_directory: ~/core
    steps:
      - checkout
      - run:
          name: Login to Docker
          command: docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
      - run:
          name: Spin up core in a local docker swarm
          command: |
            docker swarm init
            docker stack deploy -c ./Docker-Swarm/docker-compose.yml --with-registry-auth core
      - run:
          name: Wait for docker swarm to be up and running
          command: |
            echo "Waiting for Swarm to wake up..."
            SWARM_IS_DOWN="true"

            while [ "$SWARM_IS_DOWN" == "true" ]; do
              SWARM_IS_DOWN=$(curl http://localhost:9100/v1/health -s -f -o /dev/null || echo "true")
              sleep 1
            done

            echo "Swarm is up and running!"
      - run:
          name: Check health of services
          command: |
            # Check mira health
            curl -fs http://localhost:9100/v1/health
            # Check license service health
            curl -fs http://localhost:9200/v1/health
      - run:
          name: Remove deployment and leave swarm
          command: |
            docker stack rm core
            docker swarm leave --force

  # Job for testing nomad deployment of core
  nomad:
    machine: true
    working_directory: ~/core
    steps:
      - checkout
      - run:
          name: Login to Docker
          command: docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
      - run:
          name: Install Nomad
          command: |
            curl -Lo nomad.zip https://releases.hashicorp.com/nomad/0.6.3/nomad_0.6.3_linux_amd64.zip && unzip nomad.zip && chmod +x nomad && sudo mv nomad /usr/local/bin/
      - run:
          name: Start Nomad server
          command: sudo nomad agent -dev -config=./Nomad/nomad.hcl
          background: true
      - run:
          name: Deploy Core to Nomad
          command: |
            # Let the nomad agent have some time to start
            sleep 5

            # Deploy services
            sudo nomad run ./Nomad/mira.nomad
            sudo nomad run ./Nomad/license-service.nomad
            sudo nomad run ./Nomad/engine.nomad

      - run:
          name: Check health of Core services
          command: |
            # Wait for Mira to be up and running
            while [ "$CONTAINER_ID" == "" ]; do
              CONTAINER_ID=$(sudo docker ps -aqf "name=mira")
              sleep 1
            done
            echo "Mira is up and running!"

            # Check Mira health
            MIRA_URL=$(sudo docker port "$CONTAINER_ID" 9100)
            curl -fs "$MIRA_URL/v1/health"

            # Check that Mira returns correct number of qix engines
            NBR_ENGINES=$(curl "$MIRA_URL/v1/engines" | grep -o \"qix-engine\" | wc -w)
            echo "Mira returned $NBR_ENGINES qix engines"

            if [ "$NBR_ENGINES" != "2" ]; then
              echo "Incorrect number of qix engines found"
              exit 1
            fi

workflows:
  version: 2
  kubernetes_swarm_and_nomad:
    jobs:
      - kubernetes
      - swarm
      - nomad
