apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: license-service
  labels:
    app: license-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: license-service
    spec:
      containers:
      - name: license-service
        image: qlikcore/licenses:1.37.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9200
        env:
        - name: LICENSE_KEY
          valueFrom:
            configMapKeyRef:
              name: license-data
              key: LICENSE_KEY
